const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gymstant', {
  load: () => ipcRenderer.invoke('state:load'),
  save: (state) => ipcRenderer.invoke('state:save', state),
  capture: (label, privacy) => ipcRenderer.invoke('capture:screen', label, privacy),
  completeTeaching: (draft) => ipcRenderer.invoke('workflow:complete', draft),
  retireWorkflow: (workflow) => ipcRenderer.invoke('workflow:retire', workflow),
  approveLearnedWorkflow: (actionId) => ipcRenderer.invoke('workflow:approve-learned', actionId),
  executeMonitorAction: (actionId) => ipcRenderer.invoke('monitor:execute', actionId),
  askLocal: (messages, options = {}) => ipcRenderer.invoke('local:chat', { messages, options }),
  assignmentAck: (text) => ipcRenderer.invoke('assignment:ack', text),
  hermesGetModel: () => ipcRenderer.invoke('hermes:get-model'),
  hermesListModels: () => ipcRenderer.invoke('hermes:list-models'),
  hermesSetModel: (id) => ipcRenderer.invoke('hermes:set-model', id),
  hermesListTools: () => ipcRenderer.invoke('hermes:list-tools'),
  hermesSetTool: (name, enabled) => ipcRenderer.invoke('hermes:set-tool', name, enabled),
  executionBegin: () => ipcRenderer.invoke('execution:begin'),
  executionPeek: () => ipcRenderer.invoke('execution:peek'),
  executionHide: () => ipcRenderer.invoke('execution:hide'),
  executionEnd: () => ipcRenderer.invoke('execution:end'),
  executionCancel: () => ipcRenderer.invoke('execution:cancel'),
  setFocusResumeSeconds: (seconds) => ipcRenderer.invoke('settings:focus-resume', seconds),
  calendarOptions: () => ipcRenderer.invoke('calendar:options'),
  scheduleCalendar: (payload) => ipcRenderer.invoke('calendar:schedule', payload),
  loadTranscript: () => ipcRenderer.invoke('chat:load'),
  listHistory: () => ipcRenderer.invoke('chat:history'),
  archiveConversation: () => ipcRenderer.invoke('chat:archive'),
  openConversation: (id) => ipcRenderer.invoke('chat:open', id),
  openData: () => ipcRenderer.invoke('data:open'),
  resize: (expanded) => ipcRenderer.send('window:resize', expanded),
  dragStart: (point) => ipcRenderer.send('window:drag-start', point),
  dragMove: (point) => ipcRenderer.send('window:drag-move', point),
  dragEnd: () => ipcRenderer.send('window:drag-end'),
  heightResizeStart: (point) => ipcRenderer.send('window:height-resize-start', point),
  heightResizeMove: (point) => ipcRenderer.send('window:height-resize-move', point),
  heightResizeEnd: () => ipcRenderer.send('window:height-resize-end'),
  resizeStart: (payload) => ipcRenderer.send('window:resize-start', payload),
  resizeMove: (point) => ipcRenderer.send('window:resize-move', point),
  resizeEnd: () => ipcRenderer.send('window:resize-end'),
  restoreChatbar: () => ipcRenderer.invoke('window:restore-chatbar'),
  contentHeight: (height) => ipcRenderer.send('window:content-height', height),
  setChatbarHeight: (height) => ipcRenderer.send('glass:chatbar-height', height),
  refreshLens: () => ipcRenderer.invoke('lens:refresh'),
  onLens: (callback) => ipcRenderer.on('lens:frame', (_, frame) => callback(frame)),
  onPlacement: (callback) => ipcRenderer.on('window:placement', (_, placement) => callback(placement)),
  onWindowMode: (callback) => ipcRenderer.on('window:mode', (_, mode) => callback(mode)),
  onCollapsed: (callback) => ipcRenderer.on('window:collapsed', callback),
  onExecutionActivity: (callback) => ipcRenderer.on('execution:activity', (_, activity) => callback(activity)),
  onFocusResume: (callback) => ipcRenderer.on('execution:focus-resumed', (_, detail) => callback(detail)),
  onShortcutCapture: (callback) => ipcRenderer.on('capture:shortcut', callback)
});
